CREATE TABLE IF NOT EXISTS shop.person
(
    id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    username character varying(20),
    password character varying(250),
    role character varying(30)  NOT NULL,
    phone character varying(15) ,
    email character varying(40) ,
    CONSTRAINT person_pkey PRIMARY KEY (id)
);


CREATE TABLE IF NOT EXISTS shop.product
(
    id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ,
    name character varying(50) ,
    description character varying ,
    price numeric,
    created_at date default current_timestamp,
    path_img character varying(300) ,
    CONSTRAINT product_pkey PRIMARY KEY (id)
);
